language: java

os:
  - linux
  - osx

before_install:
  - brew update && brew bundle
  
cache:
  yarn: true
  directories:
    - node_modules
jdk:
  - oraclejdk8

notifications:
  email: false
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
