language: java

os:
  - linux
  - osx

jdk:
  - oraclejdk8
  
install: yarn --ignore-optional --pure-lockfile --production

notifications:
  email: false
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
