codecov:
  ui:
    # hide cyclomatic complexity in the UI and pull request comments
    hide_complexity: true

coverage:
  status:
    project:
      default: false
    patch:
      default: false

flags:
  production:
    paths:
      - src/
  test:
    paths:
      - test/
